---
- name: Ensures grafana dir exists
  file:
    path: "{{ grafana_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Ensures prometheus dir exists
  file:
    path: "{{ prometheus_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Create the monitoring network
  docker_network:
    name: monitoring

- name: Create the web network
  docker_network:
    name: web

- name: Create the grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    restart_policy: unless-stopped
    networks:
      - name: web
      - name: monitoring
    labels:
      traefik.frontend.rule: "Host:{{ grafana_url }}"
      traefik.docker.network: "web"
      traefik.port: "3000"
      traefik.enable: "true"

- name: Adding prometheus.yml file
  template:
    src: ../templates/prometheus.yml.j2
    dest: "{{ prometheus_dir }}/prometheus.yml"

- name: Create the prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    restart_policy: unless-stopped
    networks:
      - name: monitoring
      - name: web
    volumes:
      - "{{ prometheus_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml"

- name: Create the cadvisor container
  docker_container:
    name: cadvisor
    image: google/cadvisor
    restart_policy: unless-stopped
    networks:
      - name: monitoring
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

- name: Create the node-exporter container
  docker_container:
    name: node-exporter
    image: prom/node-exporter
    restart_policy: unless-stopped
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - name: monitoring
